=== mvsanjani/25075A0523/week10/week6/bookstore.dtd
<!ELEMENT bookstore (book+)>

<!ELEMENT book (title, author, price)>

<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT price (#PCDATA)>

=== mvsanjani/25075A0523/week10/week6/bootkstore_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE bookstore SYSTEM "bookstore.dtd">

<bookstore>
    <book>
        <title>Java Programming</title>
        <author>James</author>
        <price>500</price>
    </book>

    <book>
        <title>Web Development</title>
        <author>John</author>
        <price>400</price>
    </book>
</bookstore>
